{
    "log": {
      "level": 'verbose', # verbose, info, warn, error
      "fileOut": true,
      "fileName": "app.log",
      "maxSize": 15728640, # 15M bytes
      "maxFiles": 5
    },
    "device": {
      "mock": false,
      "vendorId": 0x0403,
      "productId": 0xcc4a,
      "baudRate": 15625

    },
}