{
  "app": {
    "port": 3000,
    "displayItems": [  # see [MutRequests] at src/mutClient.ts
      {
        "name": "CoolantTemperature",
        "intervalMs": 1000
      },
      {
        "name": "BatteryLevel",
        "intervalMs": 15000
      },
      {
        "name": "MafAirTemperature",
        "intervalMs": 1000
      },
      {
        "name": "FuelConsumption",
        "intervalMs": 5000
      },
    ]
  },
  "log": {
    "level": 'info', # verbose, info, warn, error
    "fileOut": true,
    "fileName": "app.log",
    "maxSize": 15728640, # 15M bytes
    "maxFiles": 5
  },
  "device": {
    "mock": false,
    "vendorId": 0x0403,
    "productId": 0xcc4a,
    "baudRate": 15625
  }
}